spring:
  cloud:
    stream:
      function:
        definition : notificationProcessor
      bindings:
        notificationProcessor-in-0:
          destination: message-event
        notificationProcessor-out-0:
          destination: notification-event

server:
  port: 8082