spring:
  cloud:
    stream:
      function:
        definition : messageSupplier;notificationEventConsumer
      bindings:
        messageSupplier-out-0:
          destination: message-event
        notificationEventConsumer-in-0:
          destination: notification-event