services:
  spring-service:
    build: ./spring-cloud-config-server/spring-cloud-config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8888/application/default" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      spring-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:8761" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
  api-gateway-service:
    build: ./api-gateway-service/api-gateway-service
    ports:
      - "9000:9000"
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:9000/load" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
  auth-service:
    build: ./auth-service/auth-service
    ports:
      - "8080:8080"
    depends_on:
      api-gateway-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:8080/api/v1/auth/load" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      auth-service:
        condition: service_healthy