version: "3.9"

services:
  spring-service:
    build: ./spring-cloud-config-server/spring-cloud-config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8888/application/default" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      spring-service:
        condition: service_healthy