services:
  spring-service:
    build: ./spring-cloud-config-server/spring-cloud-config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8888/application/default" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 256M
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      spring-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:8761" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 256M
  api-gateway-service:
    build: ./api-gateway-service
    ports:
      - "9000:9000"
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:9000/load" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 256M
  auth-service:
    build: ./auth-service/auth-service
    ports:
      - "8080:8080"
    depends_on:
      api-gateway-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:8080/api/v1/auth/load" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 256M
  message-service:
    build: ./message-service
    ports:
      - "8085:8085"
    depends_on:
      auth-service:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
#  notification-service:
#    build: ./notification-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      auth-service:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 256M
  prisoner-service:
    build: ./prisoner-service
    ports:
      - "8084:8084"
    depends_on:
      auth-service:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
#  system-event-service:
#    build: ./system-events-ver2
#    ports:
#      - "5000:5000"
#    depends_on:
#      auth-service:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 256M
  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      auth-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:8082/api/v1/users" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 256M
#  frontend:
#    build: ./frontend
#    ports:
#      - "3000:3000"
#    depends_on:
#      user-service:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 512M